### ISSUE TITLE
Unable to install odk2stata

### ISSUE THREAD

**Issue by ashishstats** [jkpr/odk2stata#4]
Hi, My name is Ashish, and using python 3.10 on Windows 10.

I tried installing odk2stata using the instructions given on https://github.com/jkpr/odk2stata. I tried the command python -m pip install odk2stata using command prompt, but was unable to install this package.

perhaps an additional package wxPython is also unable to install and not letting odk2stata to install.
[Error odk 2 stata.docx](https://github.com/jkpr/odk2stata/files/7576505/Error.odk.2.stata.docx)

The attached screenshot may be helpful.

Ashish

**Comment by jkpr** [comment]
Looks like the error messages are suggesting you install Microsoft C++ build tools 14.2 or greater. Have you done that?

**Comment by ashishstats** [comment]
I have not installed or I am not aware of it. I will try.
However odk2stata runs very well on Python version 3.9.7 on same windows10 on my pc.
