### ISSUE TITLE
Value Label missing if value is 0

### ISSUE THREAD

**Issue by srpatil1976** [jkpr/odk2stata#5]
When the choice sheet has value/name 0 (say, list_name = yn, name = 0  and 1, and label = No and 1 Yes), the DO file created does not recognize 0.  For example, the DO file created by ODK2STATA has this  - **label define yn 1 "1"** However, we should have - **label define yn 0 "No" 1 "Yes"**. @jkpr - can you please help?

This is the first time I am using GitHub or submitting a request so please pardon if I have not followed any norm/rule. Unfortunately, I dont know any coding to contribute myself

**Comment by jkpr** [comment]
Thanks for sending a message. I'll take a look

**Comment by jkpr** [comment]
I have made a fix. See https://github.com/jkpr/odk2stata/commit/c760f138cdb7fba54f3fb90ba6de12948ec6803e

<img width="536" alt="Screen Shot 2022-01-09 at 12 06 28 AM" src="https://user-images.githubusercontent.com/3988950/148671277-9477bdb3-232f-4506-acc2-04aceb393dba.png">

Make sure you upgrade the package and get version 0.2.6
